In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights.csv")

print(df.shape)
print(df.isnull().sum().sort_values(ascending=False).head(15))

(1048575, 31)
CANCELLATION_REASON    1008048
LATE_AIRCRAFT_DELAY     820047
WEATHER_DELAY           820047
AIRLINE_DELAY           820047
AIR_SYSTEM_DELAY        820047
SECURITY_DELAY          820047
ELAPSED_TIME             43071
AIR_TIME                 43071
ARRIVAL_DELAY            43071
WHEELS_ON                41296
TAXI_IN                  41296
ARRIVAL_TIME             41296
WHEELS_OFF               40229
TAXI_OUT                 40229
DEPARTURE_TIME           39515
dtype: int64

In [5]:
# creating a clean CSV
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights.csv"
)

df = df.replace(r'^\s*$', np.nan, regex=True)

df.to_csv(
    r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights_clean.csv",
    index=False
)

print("Clean file created successfully")
print(df.shape)

Clean file created successfully
(1048575, 31)

In [6]:
# size 
import os

file_path = r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights_clean.csv"

size_mb = os.path.getsize(file_path)/(1024*1024)

print(f"File Size: {size_mb:.2f} MB")

File Size: 123.68 MB

In [7]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights_clean.csv"
)

print(df[['AIR_SYSTEM_DELAY',
          'SECURITY_DELAY',
          'AIRLINE_DELAY',
          'WEATHER_DELAY',
          'LATE_AIRCRAFT_DELAY']].head(10))

   AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  WEATHER_DELAY  \
0               NaN             NaN            NaN            NaN
1               NaN             NaN            NaN            NaN
2               NaN             NaN            NaN            NaN
3               NaN             NaN            NaN            NaN
4               NaN             NaN            NaN            NaN
5               NaN             NaN            NaN            NaN
6               NaN             NaN            NaN            NaN
7               NaN             NaN            NaN            NaN
8               NaN             NaN            NaN            NaN
9               NaN             NaN            NaN            NaN

   LATE_AIRCRAFT_DELAY
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN

In [9]:
print(df.dtypes)

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                    str
FLIGHT_NUMBER            int64
TAIL_NUMBER                str
ORIGIN_AIRPORT             str
DESTINATION_AIRPORT        str
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
WHEELS_OFF             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE                 int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON        str
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [10]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 31 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   YEAR                 1048575 non-null  int64
 1   MONTH                1048575 non-null  int64
 2   DAY                  1048575 non-null  int64
 3   DAY_OF_WEEK          1048575 non-null  int64
 4   AIRLINE              1048575 non-null  str
 5   FLIGHT_NUMBER        1048575 non-null  int64
 6   TAIL_NUMBER          1040825 non-null  str
 7   ORIGIN_AIRPORT       1048575 non-null  str
 8   DESTINATION_AIRPORT  1048575 non-null  str
 9   SCHEDULED_DEPARTURE  1048575 non-null  int64
 10  DEPARTURE_TIME       1009060 non-null  float64
 11  DEPARTURE_DELAY      1009060 non-null  float64
 12  TAXI_OUT             1008346 non-null  float64
 13  WHEELS_OFF           1008346 non-null  float64
 14  SCHEDULED_TIME       1048573 non-null  float64
 15  ELAPSED_TIME         1005504 non-null  float64
 16  AIR_TIME             1005504 non-null  float64
 17  DISTANCE             1048575 non-null  int64
 18  WHEELS_ON            1007279 non-null  float64
 19  TAXI_IN              1007279 non-null  float64
 20  SCHEDULED_ARRIVAL    1048575 non-null  int64
 21  ARRIVAL_TIME         1007279 non-null  float64
 22  ARRIVAL_DELAY        1005504 non-null  float64
 23  DIVERTED             1048575 non-null  int64
 24  CANCELLED            1048575 non-null  int64
 25  CANCELLATION_REASON  40527 non-null    str
 26  AIR_SYSTEM_DELAY     228528 non-null   float64
 27  SECURITY_DELAY       228528 non-null   float64
 28  AIRLINE_DELAY        228528 non-null   float64
 29  LATE_AIRCRAFT_DELAY  228528 non-null   float64
 30  WEATHER_DELAY        228528 non-null   float64
dtypes: float64(16), int64(10), str(5)
memory usage: 248.0 MB
None

In [11]:
!pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sneha\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.14.1)
Downloading sqlalchemy-2.0.50-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 1.5 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.1 MB 1.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.9 MB/s eta 0:00:00
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.1-cp312-cp312-win_amd64.whl (238 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.5.1 pymysql-1.2.0 sqlalchemy-2.0.50

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("india@123")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/airline_analysis"
)

with engine.connect() as conn:
    print("Connection Successful!")

Connection Successful!

In [15]:
import pandas as pd

pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM flights",
    engine
)

   total_rows
0           0

In [16]:
import pandas as pd

file_path = r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights_clean.csv"

df_test = pd.read_csv(file_path, nrows=1000)

df_test.to_sql(
    name="flights",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

print("1000 rows loaded successfully")

1000 rows loaded successfully

In [17]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM flights",
    engine
)

   total_rows
0        1000

In [18]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE flights"))

print("Flights table cleared")

Flights table cleared

In [19]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM flights",
    engine
)

   total_rows
0           0

In [20]:
# importing full file
import pandas as pd

file_path = r"C:\Users\sneha\3D Objects\Desktop\career\Airline_performance_analysis\Dataset\flights_clean.csv"

chunk_size = 50000

for i, chunk in enumerate(pd.read_csv(file_path, chunksize=chunk_size)):
    chunk.to_sql(
        name="flights",
        con=engine,
        if_exists="append",
        index=False,
        method="multi"
    )
    
    print(f"Chunk {i+1} loaded")
    
print("Full dataset imported successfully!")

Chunk 1 loaded
Chunk 2 loaded
Chunk 3 loaded
Chunk 4 loaded
Chunk 5 loaded
Chunk 6 loaded
Chunk 7 loaded
Chunk 8 loaded
Chunk 9 loaded
Chunk 10 loaded
Chunk 11 loaded
Chunk 12 loaded
Chunk 13 loaded
Chunk 14 loaded
Chunk 15 loaded
Chunk 16 loaded
Chunk 17 loaded
Chunk 18 loaded
Chunk 19 loaded
Chunk 20 loaded
Chunk 21 loaded
Full dataset imported successfully!

In [21]:
# final verification
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM flights",
    engine
)

   total_rows
0     1048575